### ISSUE TITLE
does protopigeon.model_message return single instance?

### ISSUE THREAD

**Issue by tarzanjw** [jonparrott/ferris3#10]
Suppose that I have a model called Email, I do call `protopigeon.model_message(Email)` twice and it returns to me 2 different classes.

I expect that it will return the same class for 2nd call.

Is it by design ? If yes, what is the point?

```python
In[3]: import appengine_config
In[4]: import ferris3 as f3
In[5]: from app.emails.models import Email
In[6]: c1 = f3.model_message(Email)
In[7]: c2 = f3.model_message(Email)
In[8]: c1
Out[8]: protorpc.messages.EmailMessage
In[9]: c2
Out[9]: protorpc.messages.EmailMessage
In[10]: c1 is c2
Out[10]: False
In[11]: c1 == c2
Out[11]: False
In[12]: hash(c1)
Out[12]: 2796984
In[13]: hash(c2)
Out[13]: 2633612
```

**Comment by jonparrott** [comment]
protopigeon does not cache these classes upon generation. It's expected that you'd generate the model message one at the module level and re-use it.
