### ISSUE TITLE
path argument does not work with auto_method

### ISSUE THREAD

**Issue by r00tat** [jonparrott/ferris3#11]
I tried to modify the generated path for an API method, but I'm getting an error:

```
  File "/Users/frig/Documents/Zirrus/dev/google4work-trial/lib/ferris3/endpoints.py", line 220, in auto_api_decr
    **kwargs
TypeError: positional_wrapper() got multiple values for keyword argument 'path'
```

This is the part of code, that produces the error:

```
    @auto_method(returns=StatusMessage, name="domain.available", path="domain/available")
    def available(self, request, domain=(str,)):
```

If you're unable to reproduce the issue, please let me know.

**Comment by r00tat** [comment]
I had a short look in the code and saw that there was a recent change on auto_method to support the path argument. I switched to alpha 10 (named 3.0.0-a10) and it works fine now!

Thanks for that great framework!

**Comment by jonparrott** [comment]
Glad you got it sorted.
