### ISSUE TITLE
How expired Datastore cache entiry is deleted?

### ISSUE THREAD

**Issue by eyalev** [jonparrott/ferris3#19]
In here https://github.com/jonparrott/ferris3/blob/master/ferris3/caching.py#L246 the expired property is being set.

How does this entity being removed? Automatic mechanism? Cron job?

Thanks

**Comment by jonparrott** [comment]
There is currently no mechanism for clearing out expired items, that is to say, you probably shouldn't use the datastore cache on a non-deterministic number of items.
