### ISSUE TITLE
oauth2client version 2 removed module oauth2client.appengine

### ISSUE THREAD

**Issue by r00tat** [jonparrott/ferris3#27]
It seems like the most recent version of oauth2client does break the imports from oauth2.py:

```
  File "project/lib/ferris3/oauth2.py", line 41, in <module>
    from oauth2client.appengine import StorageByKeyName, CredentialsNDBProperty
ImportError: No module named appengine
```

oauth2client v1.5.2 does contain the module oauth2client.appengine. I did not trace oauth2client to the new location of the credential storage.

**Comment by r00tat** [comment]
found it, it has been moved to:
./oauth2client/contrib/appengine.py

**Comment by jonparrott** [comment]
This is a pretty straightforward fix, do you want to submit a PR for it? I'm happy to merge.

**Comment by r00tat** [comment]
Not so straightforward, it seems like SignedJwtAssertionCredentials was removed?!?

```
    from oauth2client.client import SignedJwtAssertionCredentials
ImportError: cannot import name SignedJwtAssertionCredentials
```

**Comment by r00tat** [comment]
This will change a lot for build_service_account_credentials as we need the json file itself for ServiceAccountCredentials.from_json_keyfile_name

see also https://github.com/google/oauth2client/issues/401 and https://developers.google.com/api-client-library/python/auth/service-accounts#authorizingrequests

**Comment by jonparrott** [comment]
Just use `from_json_keyfile_dict`: http://oauth2client.readthedocs.org/en/latest/source/oauth2client.service_account.html#oauth2client.service_account.ServiceAccountCredentials.from_json_keyfile_buffer

**Comment by r00tat** [comment]
Thanks Jon for that hint. I created a pull request.
