### ISSUE TITLE
Is there an easy way to make hvild wrappers more flexible?

### ISSUE THREAD

**Issue by nochristrequired** [jonparrott/ferris3#31]
Hi, I really like ferris3, but I'm struggling a bit with the hvild wrapper functions. 

```
    @ferris3.auto_method(returns=Message, name=name)
    def inner(self, request, itemId=(str,)):
        return get_impl(Model, Message, itemId)
```

For these inner functions, is there an easy way to add more parameters w/o having to write a custom inner function for each API call?

I ended up rolling my own hvild since we use CloudSQL. It works well - this is my only pain point. I have API calls that take Ids of different names, different types, and also multiple filters. I guess I could use request=(Message,) but I prefer to use HTTP GET requests for R+L functions.

Thanks in advance!

**Comment by jonparrott** [comment]
hvild was designed to be intentionally simple and easy to copy and extend as needed.
